#if !canImport(ObjectiveC)
import XCTest

extension SHA1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SHA1Tests = [
        ("testStaticBytesApi", testStaticBytesApi),
        ("testStaticDataApi", testStaticDataApi),
        ("testStreamingBytesApi", testStreamingBytesApi),
        ("testStreamingDataApi", testStreamingDataApi),
    ]
}

extension SHA2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SHA2Tests = [
        ("test256StaticBytesApi", test256StaticBytesApi),
        ("test256StaticDataApi", test256StaticDataApi),
        ("test256StreamingBytesApi", test256StreamingBytesApi),
        ("test256StreamingDataApi", test256StreamingDataApi),
        ("test512StaticBytesApi", test512StaticBytesApi),
        ("test512StaticDataApi", test512StaticDataApi),
        ("test512StreamingBytesApi", test512StreamingBytesApi),
        ("test512StreamingDataApi", test512StreamingDataApi),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SHA1Tests.__allTests__SHA1Tests),
        testCase(SHA2Tests.__allTests__SHA2Tests),
    ]
}
#endif
